version: "3"
services:
  todoapp:
    image: thoersch/tyler-todo-app:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.25"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: todoapp
      POSTGRES_DB: todoapp_prod
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - ./data:/data
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: